### PR TITLE
Output buffering support (ob_*() functions)

### PR DESCRIPTION
**Pull request by asmblah**
This PR adds support for the most common PHP-land `ob_*()` functions.

Output buffering is supported by `phpcore` using the `.output` internal, but that library does not expose anything to PHP-land - that will be done by the `outputControl` function group this PR adds.

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Review will start during next week (17th September 2018). Can not declare a definitive day, as I can only start when all my tech-stack is built up.

I'll let you know when I'm starting the review!

**Comment by IngwiePhoenix** [comment]
Performing review now. Sorry for being so late! :(

**Comment by IngwiePhoenix** [comment]
* https://github.com/uniter/phpruntime/pull/5/commits/cad99f22f8940d2699814dd0e638f7726258a5f0#diff-7a64b3c1f770ecfa432d7922e7b61592R160
  - The Buffer objects should probably receive according callbacks to when being pushed or popped in order to properly allow the callbacks to run. On node, we can use `EventEmitter`, but that would be harder on the browser as the eventing systems seem to differ? Might add a miniature polyfill within to work across the various eventing systems to allow these callbacks to be performed, essentially enabling `ob_start` to take arguments.
  - Assign callbacks as mentioned above by default, partially to keep integrity of internal data and partialy to keep a local "that's how it's done"-reminder that the user can reference. An empty callback would do perfectly. But having `Function` being the specified object type would ensure a minimal grade of type safety, I'd think...

* https://github.com/uniter/phpruntime/pull/5/commits/cad99f22f8940d2699814dd0e638f7726258a5f0#diff-e38ccef7c8940f6b52da97fdb012680dR51
  - That...looks kinda dirty :). Maybe move the shorter defines upwards to have some kind of "flow"? I believe though it's only personal preference, really. Therefore, this note is just my opinion :)

* https://github.com/uniter/phpruntime/pull/5/commits/20dd46919bea87d71d2cadeea1f1efe0f83f4ea2#diff-7a64b3c1f770ecfa432d7922e7b61592R38
  - Where'd `error` go? Make this trackable, somehow - maybe a user script is causing an exception that would otherwise stay undetected.

* https://github.com/uniter/phpruntime/pull/5/commits/20dd46919bea87d71d2cadeea1f1efe0f83f4ea2#diff-7a64b3c1f770ecfa432d7922e7b61592R61
  - Same as above.

* https://github.com/uniter/phpruntime/pull/5/commits/20dd46919bea87d71d2cadeea1f1efe0f83f4ea2#diff-7a64b3c1f770ecfa432d7922e7b61592R110
  - One more here.

* https://github.com/uniter/phpruntime/pull/5/commits/20dd46919bea87d71d2cadeea1f1efe0f83f4ea2#diff-fabb8ec59d494de36bb09257616696c6R15
  - Many, many up-steps in here. Maybe optimize this by using a package that'd allow to require from the first-found `package.json` file that was found? There's a few variants that allow that, and it'd make the code look a little bit cleaner. However, this method does NOT work in packed versions. Then again, tests usualy aren't packed :)

Alright, there's my review. :) There is ntohing that would prevent me from rejecting anything here - most of the things are either cosmetical (up-steps) or Minimal (exception tracking). Both can be solved easily!

**Review by IngwiePhoenix — APPROVED** [review]

**Comment by asmblah** [comment]
Thank you very much @IngwiePhoenix - I'll look at these tomorrow evening 😄

**Comment by asmblah** [comment]
Review comments above have been addressed/replied to as needed.

**Pull request merged**
